import  {TUser} from "./types";

export const users: TUser[] = [
  {
    id: 1,
    name: "Bell Sprull",
    role: "Admin",
    email: "bsprull0@vk.com",
    favorites: [],
    comments: [],
  },
  {
    id: 2,
    name: "Hans Abbess",
    role: "Librarian",
    email: "habbess1@sciencedaily.com",
    favorites: [],
    comments: [],
  },
  {
    id: 3,
    name: "Anissa Yitzhok",
    role: "Reader",
    email: "ayitzhok2@ft.com",
    favorites: [],
    comments: [],
  },
  {
    id: 4,
    name: "Eleonora De Beneditti",
    role: "Reader",
    email: "ede3@spotify.com",
    favorites: [],
    comments: [],
  },
  {
    id: 5,
    name: "Lannie Feaks",
    role: "Reader",
    email: "lfeaks4@arstechnica.com",
    favorites: [],
    comments: [],
  },
  {
    id: 6,
    name: "Adriane Roizin",
    role: "Reader",
    email: "aroizin5@newyorker.com",
    favorites: [],
    comments: [],
  },
  {
    id: 7,
    name: "Stormi Bellwood",
    role: "Reader",
    email: "sbellwood6@examiner.com",
    favorites: [],
    comments: [],
  },
  {
    id: 8,
    name: "Riordan Tassel",
    role: "Reader",
    email: "rtassel7@toplist.cz",
    favorites: [],
    comments: [],
  },
  {
    id: 9,
    name: "Kippie Dary",
    role: "Reader",
    email: "kdary8@mozilla.com",
    favorites: [],
    comments: [],
  },
  {
    id: 10,
    name: "Maggi Proback",
    role: "Reader",
    email: "mproback9@spotify.com",
    favorites: [],
    comments: [],
  },
  {
    id: 11,
    name: "Leia Izaks",
    role: "Reader",
    email: "lizaksa@imgur.com",
    favorites: [],
    comments: [],
  },
  {
    id: 12,
    name: "Benji Stoop",
    role: "Reader",
    email: "bstoopb@google.ru",
    favorites: [],
    comments: [],
  },
  {
    id: 13,
    name: "Aron Southcott",
    role: "Reader",
    email: "asouthcottc@biblegateway.com",
    favorites: [],
    comments: [],
  },
  {
    id: 14,
    name: "Sissie Skeemor",
    role: "Reader",
    email: "sskeemord@google.nl",
    favorites: [],
    comments: [],
  },
  {
    id: 15,
    name: "Bradney Sexon",
    role: "Reader",
    email: "bsexone@netscape.com",
    favorites: [],
    comments: [],
  },
  {
    id: 16,
    name: "Lew Greenhough",
    role: "Reader",
    email: "lgreenhoughf@yale.edu",
    favorites: [],
    comments: [],
  },
  {
    id: 17,
    name: "Emelina Kermott",
    role: "Reader",
    email: "ekermottg@unesco.org",
    favorites: [],
    comments: [],
  },
  {
    id: 18,
    name: "Ryley Yoxen",
    role: "Reader",
    email: "ryoxenh@amazon.de",
    favorites: [],
    comments: [],
  },
  {
    id: 19,
    name: "Janifer BURWIN",
    role: "Reader",
    email: "jburwini@w3.org",
    favorites: [],
    comments: [],
  },
  {
    id: 20,
    name: "Hew McKew",
    role: "Reader",
    email: "hmckewj@ox.ac.uk",
    favorites: [],
    comments: [],
  },
  {
    id: 21,
    name: "Mercie Croxton",
    role: "Reader",
    email: "mcroxtonk@wordpress.org",
    favorites: [],
    comments: [],
  },
  {
    id: 22,
    name: "Cordie de'-Ancy Willis",
    role: "Reader",
    email: "cdeancyl@issuu.com",
    favorites: [],
    comments: [],
  },
  {
    id: 23,
    name: "Clayson Pacey",
    role: "Reader",
    email: "cpaceym@squidoo.com",
    favorites: [],
    comments: [],
  },
  {
    id: 24,
    name: "Ozzie Thirst",
    role: "Reader",
    email: "othirstn@wisc.edu",
    favorites: [],
    comments: [],
  },
  {
    id: 25,
    name: "Neala Winger",
    role: "Reader",
    email: "nwingero@about.me",
    favorites: [],
    comments: [],
  }
]
